apiVersion: v1
data:
  RDS_DB_NAME: travelagency
  RDS_HOSTNAME: mysql
  RDS_PORT: "3306"
  RDS_USERNAME: travelagency-user
kind: ConfigMap
metadata:
  name: travel-agency-web-application-config
  namespace: default