apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: travel-agency-web-application
  name: travel-agency-web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: travel-agency-web-application
  template:
    metadata:
      labels:
        io.kompose.service: travel-agency-web-application
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: RDS_DB_NAME
              name: travel-agency-web-application-config
        - name: RDS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: RDS_HOSTNAME
              name: travel-agency-web-application-config
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: RDS_PASSWORD
              name: travel-agency-web-application-secrets
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              key: RDS_PORT
              name: travel-agency-web-application-config
        - name: RDS_USERNAME
          valueFrom:
            configMapKeyRef:
              key: RDS_USERNAME
              name: travel-agency-web-application-config
        image: exxperiment899/walter:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: travel-agency-web-application
        ports:
        - containerPort: 8080
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
